var languagesJSON = {
    en: {
        widgetSimpleText: 'How can I help you?',
        widgetLanguageText: '<b>How may I help you?</b><br>Choose your preferred language',
        tooltipText: 'Chat with Chip, your virtual agent',
        select: 'Select',
        exitQuestion: 'Do you really want to quit?',
        exitNo: 'No',
        exitYes: 'Yes',
        headerTitle: 'Virtual Assistant',
        headerSubtitle: 'Contact established',
        loading: 'Loading . . .',
        surveyTitle: 'Please rate you experience with the Virtual Assistant & Chat service.',
        surveyTextAreaTitle: 'Your comment',
        surveyConfirm: {
            default: 'Submit',
            filled: 'Thanks!',
            empty: 'Please rate',
        },
        surveyClose: 'Cancel',
        hint: 'Type your message here',
        resetConversation: 'Reset Conversation',
        minimalize: 'Minimalize',
        close: 'Close'
    },
    fr: {
        widgetSimpleText: 'Puis-je vous aider?',
        widgetLanguageText: 'Veuillez sélectionner la langue.',
        tooltipText: 'Chattez avec Chip, votre agent virtuel',
        select: 'Sélectionner',
        exitQuestion: 'Voulez-vous vraiment arrêter?',
        exitNo: 'Non',
        exitYes: 'Oui',
        headerTitle: 'Default Topbar Title',
        headerSubtitle: 'Default Topbar Subtitle',
        loading: 'Launching your chat...</b>',
        surveyTitle: 'Please rate you experience with the Virtual Assistant & Chat service.',
        surveyTextAreaTitle: 'Your comment',
        surveyConfirm: {
            default: 'Submit',
            filled: 'Thanks!',
            empty: 'Please rate',
        },
        surveyClose: 'Cancel',
        hint: 'Type your message here',
        resetConversation: 'Reset Conversation',
        minimalize: 'Minimalize',
        close: 'Close'
    },
    de: {
        widgetSimpleText: 'Wie kann ich Ihnen helfen?',
        widgetLanguageText: 'Bitte wählen Sie die Sprache.',
        tooltipText: 'Chatten Sie mit CHIP - Ihr Virtueller Assistent',
        select: 'wählen',
        exitQuestion: 'Möchten Sie wirklich beenden?',
        exitNo: 'Nein',
        exitYes: 'Ja',
        headerTitle: 'Virtueller Assistent',
        headerSubtitle: 'Kontakt erstellt',
        loading: 'Chat wird geladen...',
        surveyTitle: 'Bitte bewerten Sie das Gespräch.',
        surveyTextAreaTitle: 'Ihr Kommentar',
        surveyConfirm: {
            default: 'senden',
            filled: 'Danke!',
            empty: 'bewerten',
        },
        surveyClose: 'abbrechen',
        hint: 'Geben Sie Ihre Nachricht hier.',
        resetConversation: 'Konversation zurücksetzen',
        minimalize: 'minimalisieren',
        close: 'schließen'
    },
    pl: {
        widgetSimpleText: 'W czym mogę pomóc?',
        widgetLanguageText: 'Proszę wybierz język.',
        tooltipText: 'Rozmawiaj z CHIP-em - Twoim wirtualnym asystentem',
        select: 'wybierz',
        exitQuestion: 'Czy na pewno chcesz zakończyć?',
        exitNo: 'Nie',
        exitYes: 'Tak',
        headerTitle: 'Wirtualny Asystent',
        headerSubtitle: 'Kontakt nawiązany',
        loading: 'Ładuję...',
        surveyTitle: 'Proszę oceń rozmowę.',
        surveyTextAreaTitle: 'Twój komentarz',
        surveyConfirm: {
            default: 'wyślij',
            filled: 'Dziękuję!',
            empty: 'Twoja ocena',
        },
        surveyClose: 'Przerwij',
        hint: 'Wpisz swoją wiadomość tutaj.',
        resetConversation: 'Zresetuj rozmowę',
        minimalize: 'zminimalizuj',
        close: 'zamknij'
    },
    pt: {
        widgetSimpleText: 'Como posso ajudá-lo?',
        widgetLanguageText: 'Escolha o seu idioma preferido',
        tooltipText: 'Converse com Chip, seu agente virtual',
        select: 'Selecione',
        exitQuestion: 'Sair da pergunta',
        exitNo: 'Não',
        exitYes: 'Sim',
        headerTitle: 'Agente Virtual',
        headerSubtitle: 'Contato estabelecido',
        loading: 'Carregando . . .',
        surveyTitle: 'Avalie sua experiência com o serviço Virtual Assistant & Chat.',
        surveyTextAreaTitle: 'Seu comentário',
        surveyConfirm: {
            default: 'Enviar',
            filled: 'Obrigado!',
            empty: 'Por favor avalie',
        },
        surveyClose: 'Cancelar',
        hint: 'Digite aqui sua mensagem',
        resetConversation: 'Redefinir conversa',
        minimalize: 'Minimizar',
        close: 'Fechar'
    },
    it: {
        widgetSimpleText: 'Come posso aiutarti?',
        widgetLanguageText: 'Scegli la lingua',
        tooltipText: 'Parla con Chip, il tuo agente virtuale',
        select: 'Seleziona',
        exitQuestion: 'Sicuro che vuoi uscire?',
        exitNo: 'No',
        exitYes: 'Si',
        headerTitle: 'Agente Virtuale',
        headerSubtitle: 'Contatto stabilito',
        loading: 'Caricamento in corso. . .',
        surveyTitle: 'Valuta la tua esperienza con il Agente Virtuale & Chat',
        surveyTextAreaTitle: 'Tuo commento',
        surveyConfirm: {
            default: 'Invia',
            filled: 'Grazie!',
            empty: 'Valuta per favore',
        },
        surveyClose: 'Anulla',
        hint: 'Scrivi qui il tuo messaggio',
        resetConversation: 'Resetta la conversazione',
        minimalize: 'Minimizza',
        close: 'Chiudi'
    },
    jp: {
        widgetSimpleText: '何かお困りですか?',
        widgetLanguageText: '<b>何かお困りですか?</b><br>言語を選択してください',
        tooltipText: 'バーチャルアシスタントのチップとチャットを開始',
        select: '選択',
        exitQuestion: '本当に中止しますか?',
        exitNo: 'いいえ',
        exitYes: 'はい',
        headerTitle: 'バーチャルアシスタント',
        headerSubtitle: '接続が確立されました',
        loading: '読み込んでいます…',
        surveyTitle: 'バーチャルアシスタント及びチャットサービスについての評価をお願いいたします',
        surveyTextAreaTitle: 'コメント',
        surveyConfirm: {
            default: '提出',
            filled: 'ありがとうございました!',
            empty: '評価をお願いいたします',
        },
        surveyClose: 'キャンセル',
        hint: 'ここに入力してください',
        resetConversation: '会話をリセット',
        minimalize: '最小化',
        close: '閉じる'
    },
    fi: {
        widgetSimpleText: 'Kuinka voin auttaa?',
        widgetLanguageText: 'Valitkaa haluttu kieli',
        tooltipText: 'Keskustele Virtuaalisen Avustajasi Chipin kanssa',
        select: 'Valitse',
        exitQuestion: 'Haluatko varmasti lopettaa?',
        exitNo: 'Ei',
        exitYes: 'Kyllä',
        headerTitle: 'Virtuaalinen Avustaja',
        headerSubtitle: 'Yhteys muodostettu',
        loading: 'Ladataan...',
        surveyTitle: 'Arvostelethan kokemuksesi Virtuaalisen Avustajan & Chat-palvelun kanssa',
        surveyTextAreaTitle: 'Sinun kommenttisi',
        surveyConfirm: {
            default: 'Lähetä',
            filled: 'Kiitos!',
            empty: 'Arvostele',
        },
        surveyClose: 'Peruuta',
        hint: 'Kirjoita viestisi tähän',
        resetConversation: 'Nollaa keskustelu',
        minimalize: 'Minimoi',
        close: 'Sulje'
    },
    no: {
        widgetSimpleText: '',
        widgetLanguageText: '',
        tooltipText: '',
        select: '',
        exitQuestion: '',
        exitNo: '',
        exitYes: '',
        headerTitle: '',
        headerSubtitle: '',
        loading: '',
        surveyTitle: '',
        surveyTextAreaTitle: '',
        surveyConfirm: {
            default: '',
            filled: '',
            empty: '',
        },
        surveyClose: '',
        hint: '',
        resetConversation: '',
        minimalize: '',
        close: ''
    },
    sv: {
        widgetSimpleText: '',
        widgetLanguageText: '',
        tooltipText: '',
        select: '',
        exitQuestion: '',
        exitNo: '',
        exitYes: '',
        headerTitle: '',
        headerSubtitle: '',
        loading: '',
        surveyTitle: '',
        surveyTextAreaTitle: '',
        surveyConfirm: {
            default: '',
            filled: '',
            empty: '',
        },
        surveyClose: '',
        hint: '',
        resetConversation: '',
        minimalize: '',
        close: ''
    },
    ru: {
        widgetSimpleText: '',
        widgetLanguageText: '',
        tooltipText: '',
        select: '',
        exitQuestion: '',
        exitNo: '',
        exitYes: '',
        headerTitle: '',
        headerSubtitle: '',
        loading: '',
        surveyTitle: '',
        surveyTextAreaTitle: '',
        surveyConfirm: {
            default: '',
            filled: '',
            empty: '',
        },
        surveyClose: '',
        hint: '',
        resetConversation: '',
        minimalize: '',
        close: ''
    },
    dk: {
        widgetSimpleText: '',
        widgetLanguageText: '',
        tooltipText: '',
        select: '',
        exitQuestion: '',
        exitNo: '',
        exitYes: '',
        headerTitle: '',
        headerSubtitle: '',
        loading: '',
        surveyTitle: '',
        surveyTextAreaTitle: '',
        surveyConfirm: {
            default: '',
            filled: '',
            empty: '',
        },
        surveyClose: '',
        hint: '',
        resetConversation: '',
        minimalize: '',
        close: ''
    },
    nl: {
        widgetSimpleText: '',
        widgetLanguageText: '',
        tooltipText: '',
        select: '',
        exitQuestion: '',
        exitNo: '',
        exitYes: '',
        headerTitle: '',
        headerSubtitle: '',
        loading: '',
        surveyTitle: '',
        surveyTextAreaTitle: '',
        surveyConfirm: {
            default: '',
            filled: '',
            empty: '',
        },
        surveyClose: '',
        hint: '',
        resetConversation: '',
        minimalize: '',
        close: ''
    },
    ro: {
        widgetSimpleText: '',
        widgetLanguageText: '',
        tooltipText: '',
        select: '',
        exitQuestion: '',
        exitNo: '',
        exitYes: '',
        headerTitle: '',
        headerSubtitle: '',
        loading: '',
        surveyTitle: '',
        surveyTextAreaTitle: '',
        surveyConfirm: {
            default: '',
            filled: '',
            empty: '',
        },
        surveyClose: '',
        hint: '',
        resetConversation: '',
        minimalize: '',
        close: ''
    },
    sp: {
        widgetSimpleText: '',
        widgetLanguageText: '',
        tooltipText: '',
        select: '',
        exitQuestion: '',
        exitNo: '',
        exitYes: '',
        headerTitle: '',
        headerSubtitle: '',
        loading: '',
        surveyTitle: '',
        surveyTextAreaTitle: '',
        surveyConfirm: {
            default: '',
            filled: '',
            empty: '',
        },
        surveyClose: '',
        hint: '',
        resetConversation: '',
        minimalize: '',
        close: ''
    },
    mandarin: {
        widgetSimpleText: '',
        widgetLanguageText: '',
        tooltipText: '',
        select: '',
        exitQuestion: '',
        exitNo: '',
        exitYes: '',
        headerTitle: '',
        headerSubtitle: '',
        loading: '',
        surveyTitle: '',
        surveyTextAreaTitle: '',
        surveyConfirm: {
            default: '',
            filled: '',
            empty: '',
        },
        surveyClose: '',
        hint: '',
        resetConversation: '',
        minimalize: '',
        close: ''
    },
    cz: {
        widgetSimpleText: '',
        widgetLanguageText: '',
        tooltipText: '',
        select: '',
        exitQuestion: '',
        exitNo: '',
        exitYes: '',
        headerTitle: '',
        headerSubtitle: '',
        loading: '',
        surveyTitle: '',
        surveyTextAreaTitle: '',
        surveyConfirm: {
            default: '',
            filled: '',
            empty: '',
        },
        surveyClose: '',
        hint: '',
        resetConversation: '',
        minimalize: '',
        close: ''
    }
}