var languagesJSON = {
    en: {
        widgetSimpleText: 'How can I help you?',
        widgetLanguageText: '<b>How may I help you?</b><br>Choose your preferred language',
        sideBarText: "Need Help?",
        tooltipText: "Chat with Chip, your virtual agent",
        select: 'Select',
        exitQuestion: "Do you really want to quit?",
        exitNo: 'No',
        exitYes: 'Yes',
        headerTitle: 'Global Service Desk',
        headerSubtitle: '',
        loading: "Loading . . .",
        surveyTitle: 'Please rate you experience with the Virtual Assistant & Chat service.',
        surveyTextAreaTitle: 'Your comment',
        surveyConfirm: {
            default: 'Submit',
            filled: 'Thanks!',
            empty: 'Please rate'
        },
        surveyClose: 'Cancel',
        hint: 'Type your message here',
        resetConversation: 'Reset conversation',
        minimalize: 'Minimalize',
        close: 'Close'
    },
    fr: {
        widgetSimpleText: 'Puis-je vous aider?',
        widgetLanguageText: 'Veuillez sélectionner la langue.',
        tooltipText: 'Chattez avec Chip, votre agent virtuel',
        select: 'Sélectionner',
        exitQuestion: 'Voulez-vous vraiment arrêter?',
        exitNo: 'Non',
        exitYes: 'Oui',
        headerTitle: '',
        headerSubtitle: '',
        loading: 'Chargement',
        surveyTitle: 'Please rate you experience with the Virtual Assistant & Chat service.',
        surveyTextAreaTitle: 'Your comment',
        surveyConfirm: {
            default: 'Submit',
            filled: 'Thanks!',
            empty: 'Please rate',
        },
        surveyClose: 'Cancel',
        hint: 'Type your message here',
        resetConversation: 'Reset Conversation',
        minimalize: 'Minimalize',
        close: 'Close'
    },
    pl: {
        widgetSimpleText: 'W czym mogę pomóc?',
        widgetLanguageText: 'Proszę wybierz język.',
        tooltipText: 'Rozmawiaj z CHIP-em - Twoim wirtualnym asystentem',
        select: 'wybierz',
        exitQuestion: 'Czy na pewno chcesz zakończyć?',
        exitNo: 'Nie',
        exitYes: 'Tak',
        headerTitle: '',
        headerSubtitle: '',
        loading: 'Ładuję...',
        surveyTitle: 'Proszę oceń rozmowę.',
        surveyTextAreaTitle: 'Twój komentarz',
        surveyConfirm: {
            default: 'wyślij',
            filled: 'Dziękuję!',
            empty: 'Twoja ocena',
        },
        surveyClose: 'Przerwij',
        hint: 'Wpisz swoją wiadomość tutaj.',
        resetConversation: 'Zresetuj rozmowę',
        minimalize: 'zminimalizuj',
        close: 'zamknij'
    },
    it: {
        widgetSimpleText: 'Come posso aiutarti?',
        widgetLanguageText: 'Scegli la lingua',
        tooltipText: 'Parla con Chip, il tuo agente virtuale',
        select: 'Seleziona',
        exitQuestion: 'Sicuro che vuoi uscire?',
        exitNo: 'No',
        exitYes: 'Si',
        headerTitle: '',
        headerSubtitle: '',
        loading: 'Caricamento in corso. . .',
        surveyTitle: 'Valuta la tua esperienza con il Agente Virtuale & Chat',
        surveyTextAreaTitle: 'Tuo commento',
        surveyConfirm: {
            default: 'Invia',
            filled: 'Grazie!',
            empty: 'Valuta per favore',
        },
        surveyClose: 'Anulla',
        hint: 'Scrivi qui il tuo messaggio',
        resetConversation: 'Resetta la conversazione',
        minimalize: 'Minimizza',
        close: 'Chiudi'
    },
};
